### ISSUE TITLE
Support for iDeal processing?

### ISSUE THREAD

**Issue by alanta** [buckaroo-it/BuckarooSdk_DotNet#1]
Is it possible to use this SDK to access the iDeal processing service? iDeal works as expected but I can't figure out how to switch to iDeal processing.

Thanks

**Comment by sjaak-buckaroo** [comment]
Thank you for your suggestion. As previously communicated by email, the ideal processing feature has been added to the SDK.

**Comment by alanta** [comment]
Thanks, it works 👍
